### ISSUE TITLE
TypeScript definition file missing static "create", "encode" and "decode" methods

### ISSUE THREAD

**Issue by bjoyx** [dcodeIO/protobuf.js#820] opened 2017-06-02 11:10 UTC
protobuf.js version: 6.7.3

I followed the README and ran this code to compile
```
$> pbjs -t static-module -w es6 -o compiled.js file1.proto file2.proto
$> pbts -o compiled.d.ts compiled.js
```

The generated compiled.js works fine but the compiled.d.ts file is missing static methods on all the classes:

```
type Success$Properties = {
    command?: CommandMsg$Properties;
};

/**
 * Constructs a new Success.
 * @exports Success
 * @constructor
 * @param {Success$Properties=} [properties] Properties to set
 */
export class Success {

    /**
     * Constructs a new Success.
     * @exports Success
     * @constructor
     * @param {Success$Properties=} [properties] Properties to set
     */
    constructor(properties?: Success$Properties);
}

type Failure$Properties = {
    type?: Failure.ErrorCode;
    details?: string;
};

/**
 * Constructs a new Failure.
 * @exports Failure
 * @constructor
 * @param {Failure$Properties=} [properties] Properties to set
 */
export class Failure {

    /**
     * Constructs a new Failure.
     * @exports Failure
     * @constructor
     * @param {Failure$Properties=} [properties] Properties to set
     */
    constructor(properties?: Failure$Properties);
}
```

**Comment by Alexendoo** [comment] 2017-06-07 13:08
This appears to happen whenever package is not specified in a .proto file

**Comment by Lopdo** [comment] 2017-06-07 15:10
Issue I reported (#822) seems to be duplicate of this. Is that intentional behaviour? Can it be fixed so that we don't need to specify package in our .proto file?

**Comment by dcodeIO** [comment] 2017-06-07 15:30
Do you know if this also affects master? (6.8.0)

**Comment by Alexendoo** [comment] 2017-06-07 17:27
It does

**Comment by dcodeIO** [comment] 2017-06-09 09:04
Can you confirm that this fixes this issue? Feel free to reopen if it does not (fully).

**Closed** 2017-06-09 09:04 UTC
