### ISSUE TITLE
Support of google.protobuf.Any

### ISSUE THREAD

**Issue by woigl** [dcodeIO/protobuf.js#435] opened 2016-05-26 06:07 UTC
I started using proto3, but it seems that "google.protobuf.Any" datatype is not yet supported. Please let me know what I am doing wrong, ori if that is still not yet implemented.

This is my proto file:

```
syntax = "proto3";

package vnd.proto;

message Test1 {
    uint32              key = 1;
    google.protobuf.Any value   = 2;
}
```

This is my code used to read the proto file:

```
var ProtoBuf = dcodeIO.ProtoBuf;

//Synchronously
var builder = ProtoBuf.loadProtoFile("test.proto"),
    proto = builder.build("vnd.proto");
    console.log(proto);
```

This is the error I receive:
`Error: unresolvable type reference in Message.Field .vnd.proto.Test1.number: google.protobuf.Any`

Thanks in Advance.

**Comment by dcodeIO** [comment] 2016-05-26 17:18
This is not supported currently. Can you provide a link to the documentation passage on this?

**Comment by woigl** [comment] 2016-05-27 07:48
Sure, here comes the link: [https://developers.google.com/protocol-buffers/docs/proto3#any](https://developers.google.com/protocol-buffers/docs/proto3#any)

**Comment by dcodeIO** [comment] 2016-05-27 12:57
Thanks! What you can do already is to include [google/protobuf/any.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/any.proto) in your project, and import it within the file in question. Basically, it's just:

```protobuf
syntax = "proto3";
package google.protobuf;
message Any {
  string type_url = 1;
  bytes value = 2;
}
```

You are then able to work with the Any type manually until a better mechanism is in place in protobuf.js.

**Comment by woigl** [comment] 2016-05-28 06:26
Thanks for the idea.
What timeframe you assume for the implementation of the Any support in protobuf.js?

**Comment by woigl** [comment] 2016-06-03 07:55
I would highly appreciate, if someone could schedule this as a further enhancement.

**Comment by giorgosera** [comment] 2016-08-19 15:10
👍 Need this too.

**Comment by giorgosera** [comment] 2016-08-23 17:03
It's not very clear to me what's the optimal way to use the workaround mentioned above. I have a working project below:

`myservice.proto`
```
syntax = "proto3";  

package myservice;

message Any {
  string type_url = 1;
  bytes value = 2;
}

message Request {
    string id = 1;
}

message SampleA {
    string fieldA = 1;
}

message SampleB {
    string fieldB = 1;
}

message Response {
    string id = 1;
    repeated Any samples = 2;
}

service MyService {
  rpc Get (Request) returns (Response);
}
```

server.js

```javascript
const path = require('path');
const grpc = require('grpc');
const server = new grpc.Server();
const myService = grpc.load(path.join(__dirname, './myservice.proto')).myservice;
const Any = myService.Any;
const SampleA = myService.SampleA;
const SampleB = myService.SampleB;

const pack = (message, prefix) => {
  return new Any({
    type_url: path.join((prefix || ''), message.toString()),
    value: message.encode()
  });
};

server.addProtoService(myService.MyService.service, {
    get: (call, cb) => {
      const msgA = new SampleA({fieldA: 'testa'});
      const msgB = new SampleB({fieldB: 'testb'});
      const samples = [pack(msgA), pack(msgB)];
      const res = {
        id: '1234',
        samples: samples
      };
      cb(null, res);
    }
});

server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure());
server.start();

```

client.js

```javascript
const path = require('path');
const grpc = require('grpc');
const myService = grpc.load(path.join(__dirname, './myservice.proto')).myservice;

const client = new myService.MyService('0.0.0.0:50051', grpc.credentials.createInsecure());

const unpack = (message) => {
  const builder = myService[message.type_url.split('.')[2]];
  return builder.decode(message.value);
};

client.get({
  id: '1234'
}, (err, res) => {
  if (err) {
    console.log('err: ', err);
  } else {
    res.samples = res.samples.map((sample) => {
      return unpack(sample);
    });
    console.log(res);
  }
});
```

This works and I get back what I expected. However, I have a couple of questions:

1. Is there a better way to get the full name of a message to construct the `type_url`. I had a look at the implementations of other languages and messages seem to have some kind of getter for the name.

2. When encoding and decoding an Any message should I use `.encode` and `.decode` or is there a better way? 

I'll appreciate your input on this!

**Comment by dcodeIO** [comment] 2016-11-28 17:25
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Closed by dcodeIO** 2016-11-28 17:25 UTC

**Comment by sp3c1** [comment] 2018-06-06 09:28
is this working now?

**Comment by kheyse-oqton** [comment] 2018-06-18 07:39
It doesn't seem to work as expected yet: https://github.com/dcodeIO/protobuf.js/issues/764

**Comment by psaelango** [comment] 2018-07-11 00:11
loadProtoFile and build are not working in the latest version (https://github.com/matrix-io/matrix-creator-malos/issues/53). So can someone please provide example to use google.protobuf.any.

**Comment by txiaocao** [comment] 2018-08-29 02:43
+1

**Comment by live680g** [comment] 2022-02-25 06:32
> +1

+1

**Comment by live680g** [comment] 2022-02-25 10:11
It's likely that I find ways to solve the `Support of google.protobuf.Any` problem.

Below are the detail ways.

for example, i want to serialize a JS Object depending .proto file like this.
```protobuf
syntax = "proto3";
import "google/protobuf/any.proto";
package request

message Message {
  int32 version = 6;
  google.protobuf.Any body = 7;
}
message Heartbeat {
    int64 timestamp = 1;
    int32 expires = 2;
}
```

javascript snippet
```javascript
// serializition
const msg = new proto.request.Message()
const hb = new proto.request.Heartbeat()
hb.setTimestamp('12312421412414')
const any = new proto.google.protobuf.Any()
any.pack(hb.serializeBinary(), 'request.Heartbeat')
msg.setBody(any)
console.log(msg.serializeBinary())

// deserializition. input: byte stream
const msgInstance = proto.request.Message.deserializeBinary(bytes)
const msg = msgInstance.toObject()
let bodyInstance = null
const bodyPacked = msgInstance.getBody()
if (bodyPacked) {
    bodyInstance = bodyPacked.unpack(proto.request.Heartbeat.deserializeBinary, 'request.Heartbeat')
}
console.log({
    ...msg,
    body: bodyInstance && bodyInstance.toObject()
})
```

**Comment by live680g** [comment] 2022-02-25 10:25
I used google proto buf official solution instead of `protobuf.js` npm package, I also didn't find the solution to `Support of google.protobuf.Any` problem.

**Comment by live680g** [comment] 2022-08-31 01:48
Finally, I used `protobuf.js` npm package to solve the `Support of google.protobuf.Any` problem.

1. Firstly, generated static code `pbjs -t static-module -w commonjs -o compiled.js file1.proto file2.proto`, `pbts -o compiled.d.ts compiled.js`
2. Secondly, import compiled.js file
```typescript
import { request } './compiled';

// serializition
const message = request.Message.create({ version: 1 });
const heartbeat = request.Heartbeat.create({ timestamp: '123',  expires: 123}); 
message.body = {
  type_url: 'type.googleapis.com/dispatcher.Heartbeat',
  value: request.Heartbeat.encode(heartbeat).finish()
};
const buffer = request.Message.encode(message).finish();

// deserializition
const message = request.Message.decode(buffer);
const heartbeat = request.Heartbeat.decode(message.body.value);

```

**Comment by gaochongGithub** [comment] 2022-10-22 09:49
helped me a lot, thanks a lot

**Comment by ansemjo** [comment] 2024-08-10 11:33
While evaluating protobuf.js for a project, I also stumbled upon this issue in search for information how to use `google.protobuf.Any` and whether there are any `pack`/`unpack` methods. So I'll leave this info here, even if the issue is closed.

For packing a Message in a somewhat typesafe way in TypeScript, you could use this snippet:
```typescript
interface SomeProtoType {
  new (...args: any[]): any;
  getTypeUrl(prefix: string): string;
  encode(message: InstanceType<this>): pbWriter;
}

function packAny<T extends SomeProtoType>(proto: T, instance: InstanceType<T> | ConstructorParameters<T>[0]) {
  return <proto.google.protobuf.IAny>{
    type_url: proto.getTypeUrl("prefix"),
    value: proto.encode(instance).finish(),
  };
};

// usage example:
import { google, HelloRequest } from "./messages";
let any: google.protobuf.IAny = packAny(HelloRequest, { name: "Alice" });
```

This is conceptually similar to what [`bufbuild` does with its schema arguments](https://github.com/bufbuild/protobuf-es/blob/main/MANUAL.md#googleprotobufany). For unpacking, I resorted to a `switch` statement on the `.type_url` property for testing. Though you should be able to write something with [`lookup`](https://github.com/protobufjs/protobuf.js/blob/0a0cdb6b0c635d86a9bb96a382b4ff73ee848109/index.d.ts#L813), which unpacks the correct type automatically, if it is known.

I also found wrappers for the `google.protobuf.Any` type in the code but I couldn't figure out how you're supposed to use those yet: https://github.com/protobufjs/protobuf.js/blob/0a0cdb6b0c635d86a9bb96a382b4ff73ee848109/src/wrappers.js#L39-L102
