### ISSUE TITLE
serialize service method parameter  and deserialize from server

### ISSUE THREAD

**Issue by strWA** [dcodeIO/protobuf.js#300] opened 2015-07-07 13:02 UTC
I try to run service method on server. I create Request object and i am trying to add service parameters which are : type, signature, instance, method, pbin and serverRoutAddr. But when i send it to server I always get error which is "deserializing pbin failed" from server. 

I realize that the signature (fixed32) is the main problem of that situation. Because I change it to int32 it works. What is the problem?

RpcMessage.proto file :

---

``` ruby
package RpcMessage;
message Request {
    enum Type {
        RT_REQ       = 1;
        RT_SIGNATURE = 2;
    };

    optional Type type = 1 [default = RT_REQ];
    optional fixed32 signature = 2 [default = 0];
    optional string instance = 3;
    optional string method = 4;
    optional bytes pbin = 5;
    optional string serverRouteAddr = 6;
}
```

IAuth.proto file:

---

``` ruby
package IAuth;
message Name {
    required string name = 1;
}

service Impl {
    rpc user (Name) returns (User) {
        option (core.rpcdoc) = "Get user data.";
        option (core.auth) = true; // user or member of the admin group
    }
}
```

main.js file:

---

``` ruby
var RPC = ProtoBuf.loadProtoFile('../proto/RpcMessage.proto');
var authProto = ProtoBuf.loadProtoFile('../proto/IAuth.proto');
var _Request = RPC.build('RpcMessage.Request');
var _Name = authProto.build('IAuth.Name');

var name = new _Name("name");
var type = _Request.Type.RT_REQ;


  var msg = new _Request(
      {
          type:type, //enum value
          signature: 754793469, //Problem is here! 
          instance : "Auth",  //package name
          method : "user",  //method name which i try to run
          pbin : name.encode().toBinary(),
          serverRouteAddr: "address"
      });

var buffer = msg.encode();
var data = buffer.toBinary();

$.ajax({
            url: url,
            type: 'POST',
            data: data, 
            dataType: 'text',
            crossDomain: true,
            success: success
            error: onError
});


 function str2ab(str) {
            var buf = new Uint8Array(str.length);
            for (var i=0, strLen=str.length; i<strLen; i++) {
                buf[i] = str.charCodeAt(i);
            }
            return buf;
        }
```

**Comment by strWA** [comment] 2015-07-08 10:09
if signature is 0, it works but  signature is 493813054 number it is not working.

**Comment by strWA** [comment] 2015-07-08 14:18
problem is fixed32. It works on int32 also uint32. Why encoding not working at these type: fixed32, sfixed32, float?

**Comment by englercj** [comment] 2015-07-08 14:32
Can you use code blocks around your code in your original post, it is very difficult to read. You can see the syntax [here](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by strWA** [comment] 2015-07-08 15:02
Ok i changed it

**Comment by dcodeIO** [comment] 2015-07-13 18:16
One thing I notice when flying over this briefly is that you are using two different builders.

```js
var RPC = ProtoBuf.loadProtoFile('../proto/RpcMessage.proto');
var authProto = ProtoBuf.loadProtoFile('../proto/IAuth.proto');
```

In case you intend to use Request / IAuth referencing each other, this should be:

```js
var builder = ProtoBuf.loadProtoFile('../proto/RpcMessage.proto');
ProtoBuf.loadProtoFile('../proto/IAuth.proto', builder);
```

Another thing I noticed is that you are converting pbin to a binary **string** here:

```js
pbin : name.encode().toBinary(),
```

Which is wrong in context of `optional bytes pbin = 5;` and should rather be a buffer:

```js
pbin : name.encode()
```

The later is probably the cause that decoding pbin fails.

**Comment by dcodeIO** [comment] 2016-11-28 17:19
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Closed by dcodeIO** 2016-11-28 17:19 UTC
Labels: question
