### ISSUE TITLE
proto3 repeated field cause error Illegal wire type for field Message.Field

### ISSUE THREAD

**Issue by ryanouyang** [dcodeIO/protobuf.js#476] opened 2016-10-14 16:32 UTC
```
syntax = "proto3";

package com.jiaojiaoapp.protobuftest;

message ProtobufTest {
    float num = 1;
    bytes payload = 2;
    repeated int32 scores = 3;
}
```

``` javascript
var builder = ProtoBuf.loadProtoFile(path.join(__dirname, "protobuftest.proto")),
    Message = builder.build("com.jiaojiaoapp.protobuftest");
    var message = new Message.ProtobufTest({
        num: 1,
        payload: new Buffer('helloworld')
    });
    message.scores.push(1);
    message.scores.push(2);
```

this will cause error

> [Error: Illegal wire type for field Message.Field .com.jiaojiaoapp.protobuftest.ProtobufTest.scores: 2 (0 expected)]

**Comment by ryanouyang** [comment] 2016-10-15 01:52
resolved after add `[packed=true]`, no more errors.
```
syntax = "proto3";

package com.jiaojiaoapp.protobuftest;

message ProtobufTest {
    float num = 1;
    bytes payload = 2;
    repeated int32 scores = 3 [packed=true];
}
```
but i think should treat it as packed by default as the [google docs](https://developers.google.com/protocol-buffers/docs/proto3#specifying-field-rules) says:

> In proto3, repeated fields of scalar numeric types use packed encoding by default.

>

**Comment by tanis2000** [comment] 2016-10-31 19:36
Yes, according to Google docs, when using `syntax = "proto3"` the default behavior should be to consider repeated fields as `[packed=true]`
Any chance of this being corrected?

**Comment by jdimond** [comment] 2016-11-02 23:30
Related: #390

**Comment by codeka** [comment] 2016-11-12 05:21
I think this is a dupe of #432.

**Comment by dcodeIO** [comment] 2016-11-28 17:27
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Closed by dcodeIO** 2016-11-28 17:27 UTC
