### ISSUE TITLE
TypeError: parent.setOption is not a function

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#655] opened 2017-01-21 07:21 UTC
protobuf.js version: 6.5.3, Does not happen in 6.5.0

```
/Users/robinanil/work/core/node_modules/protobufjs/cli/pbjs.js:168
            throw err;
            ^

TypeError: parent.setOption is not a function
    at parseOptionValue (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:511:20)
    at parseOption (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:493:9)
    at parseInlineOptions (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:518:17)
    at parseEnumValue (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:470:9)
    at parseEnum (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:451:21)
    at parseCommon (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:248:17)
    at parseType (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:272:21)
    at parseCommon (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:244:17)
    at parse (/Users/robinanil/work/core/node_modules/protobufjs/src/parse.js:676:21)
    at process (/Users/robinanil/work/core/node_modules/protobufjs/src/root.js:115:30)
```

**Comment by dcodeIO** [comment] 2017-01-21 14:04
For reference, caused by inline enum value options:

```protobuf
enum MyEnum {
   ONE = 1 [foo="bar"];
}
```

**Comment by dcodeIO** [comment] 2017-01-24 00:49
Closing this for now because it should be fixed in master. Once there is a release, feel free to reopen if there are still any issues.

**Closed by dcodeIO** 2017-01-24 00:49 UTC
Labels: bug
